baseURL = "https://latidudemaps.github.io/"
title = "LOGO HERE"
theme = "PaperMod"
languageCode = "en-us"

[params]
defaultTheme = "dark"
disableThemeToggle = true
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true

[params.theme_config]
background = "/images/background.jpg"

[params.assets]
disableHLJS = true
customCSS = ["css/custom.css"]

# Homepage settings
[params.profileMode]
enabled = true
title = "Michele Tricarico"
subtitle = "Geologist / GIS Specialist"
imageUrl = "images/profilepic.jpg"
imageTitle = "my image"

[[params.profileMode.buttons]]
name = "Portfolio"
url = "/portfolio"

[[params.profileMode.buttons]]
name = "Blog"
url = "/posts"

[[params.profileMode.buttons]]
name = "About"
url = "/about"

# Main menu
[menu]
[[menu.main]]
identifier = "portfolio"
name = "Portfolio"
url = "/portfolio/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 30

# Updated Social Icons section
[params.social]
github = "latidudemaps"
email = "latidude.maps@gmail.com"